#define TOK_INT 1
#define TOK_IF 2
#define TOK_ELSE 3
#define TOK_EQUAL 4
#define TOK_COMMA 5
#define TOK_SEMICOLON 6
#define TOK_ID 7
#define TOK_LEFTBKT 8
#define TOK_RIGHTBKT 9
#define TOK_LEFTCRL 10
#define TOK_RIGHTCRL 11
#define TOK_INCREMENT 12
#define TOK_ADD 13
#define TOK_COMPARISON 14
#define TOK_PLUS_INCR 15
#define TOK_WHILE 16
#define TOK_FOR 17
#define TOK_DIGIT 18
#define TOK_RETURN 19